version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: eduardo
      MONGO_INITDB_ROOT_PASSWORD: eduardo
    ports:
      - 27017:27017
    volumes:
      - ./mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ./db-dump:/db-dump

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: eduardo
      ME_CONFIG_MONGODB_ADMINPASSWORD: eduardo
      ME_CONFIG_MONGODB_URL: mongodb://eduardo:eduardo@mongo:27017/
